model_version: "v1.0.0"
choose_model: "LogisticRegression"
method:
  - name: "LogisticRegression"
    params:
      max_iter: 1000
  - name: "RandomForestClassifier"
    params:
      n_estimators: 100
      max_depth: 10
  - name: "SVC"
    params:
      kernel: "linear"
      C: 1.0
  - name: "MultinomialNB"
    params:
      alpha: 1.0
  - name: "KNeighborsClassifier"
    params:
      n_neighbors: 5
      weights: "uniform"
      algorithm: "auto"
  - name: "DecisionTreeClassifier"
    params:
      criterion: "gini"
      max_depth: 10
      min_samples_split: 2
      
